//! M3 on-chain Groth16 verifier (OPAQ.md B.6 isolation test).
//!
//! Instruction data: `proof_a(64) ‖ proof_b(128) ‖ proof_c(64) ‖ public(3×32)`
//! = 352 bytes, in the groth16-solana byte layout produced by
//! `crates/groth16-verify` (`emit_artifacts`). Returns Ok if the proof verifies
//! against the embedded deposit VK, Custom(1) otherwise.

use groth16_solana::groth16::{Groth16Verifier, Groth16Verifyingkey};
use solana_program::{
    account_info::AccountInfo, entrypoint, entrypoint::ProgramResult, msg,
    program_error::ProgramError, pubkey::Pubkey,
};

mod vk; // generated by emit_artifacts (INSECURE test vk — see B.6 caveat)

const VERIFYINGKEY: Groth16Verifyingkey<'static> = Groth16Verifyingkey {
    nr_pubinputs: 3,
    vk_alpha_g1: vk::VK_ALPHA_G1,
    vk_beta_g2: vk::VK_BETA_G2,
    vk_gamme_g2: vk::VK_GAMME_G2,
    vk_delta_g2: vk::VK_DELTA_G2,
    vk_ic: &vk::VK_IC,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    _program_id: &Pubkey,
    _accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if data.len() != 256 + 3 * 32 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let proof_a: [u8; 64] = data[0..64].try_into().unwrap();
    let proof_b: [u8; 128] = data[64..192].try_into().unwrap();
    let proof_c: [u8; 64] = data[192..256].try_into().unwrap();
    let mut public = [[0u8; 32]; 3];
    for (i, chunk) in data[256..].chunks_exact(32).enumerate() {
        public[i].copy_from_slice(chunk);
    }

    let mut verifier =
        Groth16Verifier::new(&proof_a, &proof_b, &proof_c, &public, &VERIFYINGKEY)
            .map_err(|_| ProgramError::InvalidInstructionData)?;
    match verifier.verify() {
        Ok(()) => {
            msg!("groth16: proof verified");
            Ok(())
        }
        Err(_) => {
            msg!("groth16: proof INVALID");
            Err(ProgramError::Custom(1))
        }
    }
}
